### ISSUE TITLE
interactive plots not working?

### ISSUE THREAD

**Issue by mathause** [C2SM/pyvis#102]
@chadhat : `%matplotlib widget` is not working (shown in https://github.com/C2SM/pyvis/blob/devel/Part1_Matplotlib/ex1_0_introduction.ipynb). Getting this to work may need more packages in the environment: https://codesolid.com/creating-a-python-interactive-plot/

What should we do here - try to fix this? (Do you have time to check this?) Remove this part?

**Comment by chadhat** [comment]
Ok let's remove that. It's not so important
