### ISSUE TITLE
"conda env create -f pyvis.yml" does not work 

### ISSUE THREAD

**Issue by colombsi** [C2SM/pyvis#37]
The command :
conda env create -f pyvis.yml
does not work on my personal computer. Tarun told me to use the following conda setting environment, and this works:
conda env create -f packages.yml

I added this information on the front page. 

I am not sure if both environments should be referenced on the front page, I think it could be misleading. Can we delete  the line referencing pyvis.yml ?

**Comment by colombsi** [comment]
In my last message , when I spoke about the front page, I meant the file README.md . IUt is teh latter file that I changed. 
I am sorry, I am not familiar with github yet...

**Comment by mathause** [comment]
Yes, I will have to take care of the environments. I know the problem by now.

Can you test it at the moment.

**Comment by colombsi** [comment]
Yes I could create the environment by using the packages.yml file

**Comment by mathause** [comment]
closed in #40
