### ISSUE TITLE
command line code to install environment doesn't work

### ISSUE THREAD

**Issue by felberr** [C2SM/pyvis#44]
When I call `conda env create -f packages.yml`in the command line the terminal of my MacBook. I get the following error:

```bash
Raphaels-MacBook-Pro:~ felberr$ conda env create -f packages.yml

SpecNotFound: Can't process without a name
```

The installation with the __Anaconda Navigator__ works.

**Comment by mathause** [comment]
Was the `packages.yml` avaliable in the folder you execute the command?

**Comment by felberr** [comment]
Ups, I was in the wrong directory. Changing to the right directory solved the problem. Thanks for the help.
